steps:
  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build
    parallelism: 5

  
  - block: "Blocked"
 
  - label: ":construction_worker: Unblocked"
    command: echo "Woooot"

