steps:
  - label: "Check verobot PAT expiration"
    commands: echo "Passing this test"
    notify:
      - slack:
          channels:
            - "#testing-notifications"
          message: "The GitHub PAT for verobot needs to be rotated"
