notify:
  # https://buildkite.pagerduty.com/service-directory/PANYOJ2/integrations
  - pagerduty_change_event: "136898a15c734aeea4b61fdb6111111"
    if: "build.state == 'failed'"

steps:
  - name: "Redact stuff please"
    command: 'echo 136898a15c734aeea4b61fdb6111111 | buildkite-agent redactor add; echo "pagerduty_change_event" | buildkite-agent redactor add'
    concurrency: 1
    concurrency_group: "packmanager/deployment/all-prod-envs"
  
  - wait
  - label: "Trigger step"
    trigger: "starter"
    soft_fail: true
  
  - name: "Inside group, after trigger"
    command: "echo 'Do something else'; sleep 10"
  - wait
  
  - name: "After wait, sleep"
    command: "echo 'Do something else'; sleep 10"
    
  - name: "END"
    command: "echo 'End of concurrency gate'"
    concurrency: 1
    concurrency_group: "packmanager/deployment/all-prod-envs"

  - name: "After end, sleep"
    command: "echo 'Do something else'; sleep 10"
