notify:
  # Notify user
  - slack: "@jy"
    if: build.state == "failed"
    
steps:
  - label: "Example Test - pass"
    command: echo "Hello!"; exit 1
    key: unitTests
    notify:
      - slack: "@jy"
        if: build.state == 'failed'

