steps:
  - label: "Check verobot PAT expiration"
    notify:
    - if: "build.state == 'failed'"
      slack:
        message: "The GitHub PAT for verobot needs to be rotated"
        channels:
        - "#testing-notifications"
    command: "echo \"Passing this test\" & exit 1"
