steps:
  - label: ":hammer: Stage 1"
    command: echo "Running Stage 1"

  - label: ":hammer: Stage 2"
    command: echo "Running Stage 2"

  - label: ":warning: Stage 3 - Soft Fail"
    command: |
      echo "This step will fail, but it's soft-fail configured."
      exit 1
    allow_failure: true

  - label: ":hammer: Stage 4"
    command: echo "Running Stage 4"

  - label: ":hammer: Stage 5"
    command: echo "Running Stage 5"
