steps:
  - label: "Calculate Condition Value"
    command: ./src/determine-skip.sh  # This script should output 'true' or 'false'
    artifact_paths: buildkite-env.sh

  - wait: ~

  - label: "Create Environment"
    command: "buildkite-agent artifact download buildkite-env.sh . && ./buildkite-env.sh"

  

