steps:
  - label: ":ballot_box_with_ballot:"
    command: ./src/generate-and-store-number.sh
    parallelism: 5

  - wait

  - label: ":desktop_computer:"
    command: ./src/fetch-and-display-number.sh