notify:
  # Notify user
  - slack: "@jy"
    if: build.state == "passed"
    
steps:
  - command: exit -1
    soft_fail: true
    key: 'step1'
  - command: |
     if [ $(buildkite-agent step get "outcome" --step "step1") == "soft_failed" ]; then
     cat <<- YAML | buildkite-agent pipeline upload 
     steps:
       - label: "Notify slack about soft failed step"
         command: echo "Notifying slack about the soft_failed step"
         notify:
           - slack:
               channels:
                 - "@jy"
               message: "Step1 has soft failed."
       - label: "Exit and fail"
         command: exit 1
     YAML
     fi
