steps:
  - label: "Check verobot PAT expiration"
    commands: echo "Passing this test"
    build:
      message: "[PAY-31907] Ignore job titles and $0 hourly earnings in compare_hourly_earnings_rows
        Pays parity (#256081)"
