# This should work - using dynamic pipeline upload instead of static conditionals

steps:
  - label: "ðŸ”§ Generate Pipeline Based on Conditions"
    command: |
      echo "--- :gear: Setting up environment variables"
      
      # Set custom variable based on some logic (simulating the pre-command hook)
      if [[ "${BUILDKITE_BRANCH}" == "main" ]]; then
          CUSTOM_VAR="true"
          echo "Setting CUSTOM_VAR=true for main branch"
      else
          CUSTOM_VAR="false"
          echo "Setting CUSTOM_VAR=false for non-main branch"
      fi
      
      # Set internal build number
      INTERNAL_BUILD_NUMBER="${BUILDKITE_BUILD_NUMBER}-${BUILDKITE_BRANCH}"
      echo "Set INTERNAL_BUILD_NUMBER=${INTERNAL_BUILD_NUMBER}"
      
      echo "--- :pipeline: Generating dynamic pipeline"
      
      # Now generate the pipeline based on the variables
      if [ "$CUSTOM_VAR" = "true" ]; then
        echo "Generating pipeline WITH tests"
        cat << EOF | buildkite-agent pipeline upload
      steps:
        - label: "âœ… Tests (Custom Var = true)"
          command: |
            echo "Running tests because CUSTOM_VAR=$CUSTOM_VAR"
            echo "Internal build number: $INTERNAL_BUILD_NUMBER"
            echo "Branch: ${BUILDKITE_BRANCH}"
            # Actual test commands would go here
            
        - label: "ðŸš€ Deploy"
          command: |
            echo "Deploying build $INTERNAL_BUILD_NUMBER"
            echo "Branch: ${BUILDKITE_BRANCH}"
            # Actual deploy commands would go here
      EOF
      else
        echo "Generating pipeline WITHOUT tests"
        cat << EOF | buildkite-agent pipeline upload
      steps:
        - label: "â­ï¸ Skip Tests (Custom Var = false)"
          command: |
            echo "Skipping tests because CUSTOM_VAR=$CUSTOM_VAR"
            echo "Internal build number: $INTERNAL_BUILD_NUMBER"
            
        - label: "ðŸš€ Deploy Only"
          command: |
            echo "Deploying build $INTERNAL_BUILD_NUMBER (no tests)"
            echo "Branch: ${BUILDKITE_BRANCH}"
            # Actual deploy commands would go here
      EOF
      fi