steps:
  - label: "Calculate Condition Value"
    command: ./src/determine-skip.sh  # This script should output 'true' or 'false'
    artifact_paths: buildkite-env.sh

  - wait: ~

  - label: "Setup Environment"
    command: "buildkite-agent artifact download buildkite-env.sh . && source buildkite-env.sh"

  - wait
  
  - label: "Conditionally Skipped Step"
    command: |
      source buildkite-env.sh
      echo "SHOULD_SKIP value is $SHOULD_SKIP"
      if [[ "$SHOULD_SKIP" != "true" ]]; then
        echo 'This step was not skipped.'
      else
        echo 'This step is skipped.'
      fi

