steps:

  - command: pwd
  
  - label: ":ballot_box_with_ballot:"
    command: ./src/generate-and-store-number.sh

  - wait

  - label: ":desktop_computer:"
    command: ./src/fetch-and-display-number.sh

  - command: "echo parallel test"
    label: "Test %n"
    parallelism: 5
