notify:
  # Notify user
  - slack: "@jy"
    if: build.state == "passed"
    message: "Example Test BUILD Notification"
    
steps:
  - label: "Example Test - pass"
    command: echo "Hello!"
    key: unitTests
    notify:
      - slack: "@jy"
        if: build.state == 'failed'

