notify:
  # Notify user
  - slack: "@jy"
    if: build.env(BUILDKITE_STEP_KEY) == 'unitTests' && build.state != 'failed'

steps:
  - label: "Example Test - pass"
    command: echo "Hello!"
    key: unitTests
    notify:
      - slack: "@jy"
        if: build.env(BUILDKITE_STEP_KEY) == 'unitTests' && build.state == 'failed'
