env: 
  OVERWRITE: "ORIGINAL VALUE"
steps:
  - label: ":construction_worker: Build"
    command: echo "$OVERWRITE" && export OVERWRITE="NEW VALUE"

  - label: ":white_check_mark: Test"
    command: echo "$OVERWRITE"
