steps:
  - label: ":ubuntu:"
    command: ./src/show-environment.sh
    plugins:
      - docker#v3.5.0:
          image: "ubuntu:latest"
          propagate-environment: true
          mount-buildkite-agent: true
          
  - label: ":ski: missing bash"
    command: ./src/show-environment.sh
    plugins:
      - docker#v3.5.0:
          image: "alpine:latest"
          propagate-environment: true