steps:
  - label: "Check verobot PAT expiration"
    commands: echo "Passing this test" & exit 1
    notify:
      - slack:
          channels:
            - "buildkite@jykingston"
          message: "The GitHub PAT for verobot needs to be rotated"
        if: "build.state == 'failed'"
