steps:
  - label: "Testing if this works at all"
    notify:
    - if: "build.state == 'failed'"
      slack:
        message: "Lets write a whole new message"
        channels:
        - "#testing-notifications"
    command: "echo \"Passing this test\" & exit 1"
