notify:
  # Notify user
  - slack: "@jy"
    if: build.state == "passed"

steps:
  - label: "Example Test - pass"
    command: echo "Hello!"
    key: unitTests
    notify:
      - slack: "@jy"
        if: build.state == 'failed'
        message: "Example Test Step Notification"

