steps:
  - label: ":construction_worker: Build"
    command: echo "Build the rocket"
    key: build

  - label: ":white_check_mark: Test"
    command: echo "Test the rocket"
    key: test
    depends_on: build

  - label: ":rocket: Deploy"
    command: |
      echo "Launch the rocket"
      cat .buildkite/annotation.md | buildkite-agent annotate --style "success"
    key: deploy
    depends_on: test

steps:
  - input: "How many Deployment will you do?"
    key: "check-input"
    fields:
      - select: "Number of Deployements"
        key: "deployment-total"
        options:
          - label: "1"
            value: "1"
          - label: "2"
            value: "2"

      - select: "Which Environments?"
        key: "environment-type"
        hint: "Which release stream does this belong in? :fork:"
        multiple: true
        options:
          - label: "Staging"
            value: "staging"
          - label: "Production"
            value: "prod"
          - label: "Dev"
            value: "dev"

  - command: src/test.sh
    label: "Display step"
    depends_on: check_input
