steps:
  - label: ":hammer: Stage 1"
    command: echo "Running Stage 1"

  - label: ":hammer: Stage 2"
    command: echo "Running Stage 2"

  - label: ":warning: Stage 3 - Soft Fail"
    command: sleep 60; exit 1

  - label: ":hammer: Stage 4"
    command: echo "Running Stage 4"

  - label: ":hammer: Stage 5"
    command: echo "Running Stage 5"
