steps:
  - label: ":hammer: Step 1"
    command: echo "Running Step 1"

  - label: ":hammer: Step 2"
    command: echo "Running Step 2"

  - label: ":hammer: Step 3 fail"
    command: |
      echo "This step will fail and run last"
      exit 1
    depends_on: 
      - "Step 1"
      - "Step 2"

  - label: ":hammer: Step 4"
    command: echo "Running Step 4"
    depends_on: 
      - "Step 1"
      - "Step 2"
      
  - label: ":hammer: Step 5"
    command: echo "Running Step 5"
    depends_on: 
      - "Step 1"
      - "Step 2"
