steps:
  - label: Pipeline upload
    command: buildkite-agent pipeline upload
    plugins:
      - sparse-checkout:
          paths:
            - .buildkite

  - command: exit -1
    key: 'step1'

  - command: echo "hello one"
    depends_on: step1
    key: 'step2'
